# [[plugins]]
#   package = "@netlify/plugin-functions-install-core"

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"
  base = "frontend"

  [build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200